version: '2'
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=streama
      - MYSQL_USER=streama
      - MYSQL_PASSWORD=streama
      - MYSQL_ROOT_PASSWORD=streama
  streama:
    image: sachstreama
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - /home/wiflix/Documents/sachStreama /app
      - /home/wiflix/Videos /videos
    ports:
      - 8080:8080
      - 4000:4000
    environment:
      - MYSQL_HOST=db
      - MYSQL_DB=streama
      - MYSQL_USER=streama
      - MYSQL_PASSWORD=streama
