package org.grails.cxf.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-11-30T23:41:31.677+03:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://cps.huawei.com/cpsinterface/c2bpayment", name = "C2BPaymentValidationAndComfirmation")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface C2BPaymentValidationAndComfirmation {

    @WebResult(name = "C2BPaymentValidationResult", targetNamespace = "http://cps.huawei.com/cpsinterface/c2bpayment", partName = "C2BPaymentValidationResult")
    @WebMethod(operationName = "ValidateC2BPayment", action = "ValidateC2BPayment")
    public C2BPaymentValidationResult validateC2BPayment(
        @WebParam(partName = "C2BPaymentValidationRequest", name = "C2BPaymentValidationRequest", targetNamespace = "http://cps.huawei.com/cpsinterface/c2bpayment")
        C2BPaymentValidationRequest c2BPaymentValidationRequest
    );

    @WebResult(name = "C2BPaymentConfirmationResult", targetNamespace = "http://cps.huawei.com/cpsinterface/c2bpayment", partName = "C2BPaymentConfirmationResult")
    @WebMethod(operationName = "ConfirmC2BPayment", action = "ConfirmC2BPayment")
    public java.lang.String confirmC2BPayment(
        @WebParam(partName = "C2BPaymenConfirmationRequest", name = "C2BPaymentConfirmationRequest", targetNamespace = "http://cps.huawei.com/cpsinterface/c2bpayment")
        C2BPaymentConfirmationRequest c2BPaymenConfirmationRequest
    );
}
