# Place this file next to the streama-[version].war on deployment
environments:
    production:
        dataSource:
#            driverClassName:  'com.mysql.jdbc.Driver'
#            url: jdbc:mysql://localhost/streama
#            username: root
#            password:
            driverClassName:  'org.h2.Driver'
            url: jdbc:h2:./streama;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            username: root
            password:
        server:
            port: 8080
