
package tns.ns;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LNMO_portType", targetNamespace = "tns:ns")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LNMOPortType {


    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns tns.ns.ProcessCheckOutResponse
     */
    @WebMethod
    @WebResult(name = "processCheckOutResponse", targetNamespace = "tns:ns", partName = "parameters")
    public ProcessCheckOutResponse processCheckOut(
        @WebParam(name = "processCheckOutRequest", targetNamespace = "tns:ns", partName = "body")
        ProcessCheckOutRequest body,
        @WebParam(name = "CheckOutHeader", targetNamespace = "tns:ns", header = true, partName = "header")
        CheckOutHeader header);

    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns tns.ns.TransactionStatusResponse
     */
    @WebMethod
    @WebResult(name = "transactionStatusResponse", targetNamespace = "tns:ns", partName = "parameters")
    public TransactionStatusResponse transactionStatusQuery(
        @WebParam(name = "transactionStatusRequest", targetNamespace = "tns:ns", partName = "body")
        TransactionStatusRequest body,
        @WebParam(name = "CheckOutHeader", targetNamespace = "tns:ns", header = true, partName = "header")
        CheckOutHeader header);

    /**
     * 
     * @param parameters
     * @param header
     * @return
     *     returns tns.ns.TransactionConfirmResponse
     */
    @WebMethod
    @WebResult(name = "transactionConfirmResponse", targetNamespace = "tns:ns", partName = "parameters")
    public TransactionConfirmResponse confirmTransaction(
        @WebParam(name = "transactionConfirmRequest", targetNamespace = "tns:ns", partName = "parameters")
        TransactionConfirmRequest parameters,
        @WebParam(name = "CheckOutHeader", targetNamespace = "tns:ns", header = true, partName = "header")
        CheckOutHeader header);

    /**
     * 
     * @param resultMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LNMOResult")
    @WebResult(name = "ResponseMsg", targetNamespace = "tns:ns", partName = "ResponseMsg")
    public String lnmoResult(
        @WebParam(name = "ResultMsg", targetNamespace = "tns:ns", partName = "ResultMsg")
        ResultMsg resultMsg);

}
